# Generated by Django 3.2.4 on 2021-06-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_alter_udata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udata',
            old_name='pin',
            new_name='pincode',
        ),
    ]
