# Generated by Django 3.2.4 on 2021-06-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_rename_pin_udata_pincode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='udata',
            new_name='Userdata',
        ),
    ]
